// <auto-generated />
using Devs2Blu.AgendaContato.ProjetoMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Devs2Blu.AgendaContato.ProjetoMVC.Migrations
{
    [DbContext(typeof(ContextoDatabase))]
    partial class ContextoDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Devs2Blu.AgendaContato.ProjetoMVC.Models.Entities.Compromisso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("bairro");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cidade");

                    b.Property<int>("ContatoId")
                        .HasColumnType("int")
                        .HasColumnName("ContatoId");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("Num")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("num");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rua");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("titulo");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.HasIndex("ContatoId");

                    b.ToTable("compromissos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Fortaleza",
                            CEP = "89055550",
                            Cidade = "Blumenau",
                            ContatoId = 1,
                            Descricao = "Aniversário de 53 anos",
                            Num = "180",
                            Rua = "Roseli Rosani Burkhardt",
                            Titulo = "Aniversário",
                            UF = "SC"
                        });
                });

            modelBuilder.Entity("Devs2Blu.AgendaContato.ProjetoMVC.Models.Entities.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("contatos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jose@gmail.com",
                            Nome = "José",
                            Telefone = "999999999"
                        },
                        new
                        {
                            Id = 2,
                            Email = "karina@gmail.com",
                            Nome = "Karina",
                            Telefone = "999883922"
                        });
                });

            modelBuilder.Entity("Devs2Blu.AgendaContato.ProjetoMVC.Models.Entities.Compromisso", b =>
                {
                    b.HasOne("Devs2Blu.AgendaContato.ProjetoMVC.Models.Entities.Contato", "Contato")
                        .WithMany("Compromissos")
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contato");
                });

            modelBuilder.Entity("Devs2Blu.AgendaContato.ProjetoMVC.Models.Entities.Contato", b =>
                {
                    b.Navigation("Compromissos");
                });
#pragma warning restore 612, 618
        }
    }
}
