INSERT INTO estados (id, uf, descricao) 
values 	 (2, 'AL', 'Alagos'),
		 (3, 'AP', 'Amapá'),
		 (4, 'AM', 'Amazonas'),
		 (5, 'BA', 'Bahia'),
		 (6, 'CE', 'Ceará'),
		 (7, 'DF', 'Distrito Federal'),
		 (8, 'ES', 'Espírito Santo'),
		 (9, 'GO', 'Goiás'),
		 (10, 'MA', 'Maranhão'),
		 (11, 'MT', 'Mato Grosso'),
		 (12, 'MS', 'Mato Grosso do Sul'),
		 (13, 'MG', 'Minas Gerais'),
		 (14, 'PA', 'Pará'),
		 (15, 'PB', 'Paraíba'),
		 (16, 'PR', 'Paraná'),
		 (17, 'PE', 'Pernambuco'),
		 (18, 'PI', 'Piauí'),
		 (19, 'RJ', 'Rio de Janeiro'),
		 (20, 'RN', 'Rio Grande do Sul'),
		 (21, 'RO', 'Rondônia'),
		 (22, 'RR', 'Roraima'),
		 (23, 'SC', 'Santa Catarina'),
		 (24, 'SP', 'São Paulo'),
		 (25, 'SE', 'Sergipe'),
		 (26, 'TO', 'Tocantins');

INSERT INTO estados (id, uf, descricao) value (27, 'RN', 'Rio Grande do Norte');
